config {
  type: "table",
  schema: "silver",
  name: "stg_taxi_trips",
  description: "Cleaned and standardized Chicago Taxi Trips"
}

WITH deduplicated AS (

  SELECT *
  FROM ${ref("raw_taxi_trips")}

  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY unique_key
    ORDER BY trip_start_timestamp
  ) = 1

)

SELECT

  unique_key,
  taxi_id,

  trip_start_timestamp,
  trip_end_timestamp,

  DATE(trip_start_timestamp) AS trip_date,
  EXTRACT(YEAR FROM trip_start_timestamp) AS trip_year,
  EXTRACT(MONTH FROM trip_start_timestamp) AS trip_month,
  EXTRACT(DAY FROM trip_start_timestamp) AS trip_day,
  EXTRACT(DAYOFWEEK FROM trip_start_timestamp) AS trip_day_of_week,
  EXTRACT(HOUR FROM trip_start_timestamp) AS trip_hour,

  trip_seconds,
  trip_miles,

  fare,
  tips,
  tolls,
  extras,
  trip_total,

  payment_type,

  COALESCE(company, 'Unknown') AS company,

  pickup_census_tract,
  dropoff_census_tract,

  pickup_community_area,
  dropoff_community_area,

  pickup_latitude,
  pickup_longitude,
  pickup_location,

  dropoff_latitude,
  dropoff_longitude,
  dropoff_location

FROM deduplicated

WHERE trip_start_timestamp IS NOT NULL
  AND trip_end_timestamp IS NOT NULL
  AND trip_end_timestamp >= trip_start_timestamp